services:
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "6MB"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "42MB"

  api1: &api
    build:
      context: ../api
      dockerfile: Dockerfile
    command: pnpm start
    hostname: api1
    environment:
      - PORT=9999
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://cache:6379
    networks:
      - backend
      - payment-processor
    depends_on:
      cache: { condition: service_healthy }

  api2:
    <<: *api
    hostname: api2

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
