# Docker Compose para produção usando imagens do Docker Hub
# Para desenvolvimento local, use docker-compose.dev.yml

services:
  api1: &api
    image: joaoulian/rinha-backend-2025-api:latest
    command: node dist/index.js
    hostname: api1
    environment:
      - PORT=9999
      - REDIS_URL=redis://cache:6379
    networks:
      - backend
      - payment-processor
    depends_on:
      cache:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  api2:
    <<: *api
    hostname: api2

  worker1:
    image: joaoulian/rinha-backend-2025-api:latest
    command: node dist/worker.js
    hostname: worker1
    environment:
      - REDIS_URL=redis://cache:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      cache:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "60MB"

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150MB"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
